---
title: "Introduction to VBA"
output: 
  html_document:
    toc: FALSE
---




**Welcome to my online textbook, introducing Excel VBA to accounting students!**


# Getting started

The Textbook Tab at the top contains two sub menus:  
- Markdown file: This contains text that explains all concepts, subdivided in chapters.  
- Excel files: This contains workbooks needed to complete exercises provided in the markdown file.

# Prerequisite knowledge

This textbook focuses on syntax only assumes that the reader is already familiar with the following tools necessary to work with VBA:  
- How to access the visual basic editor  
- How to add a module  
- How to place syntax into a sub procedure (all code provided in this book are assumed to be inside a sub procedure)  
- How to execute macros, e.g. assigning macro buttons

# About the Author

Hamman Schoonwinkel is a CA(SA) and lecturer at the University of Stellenbosch.

# Copyright

CC BY-NC-ND.

This license allows reusers to copy and distribute the material in any medium or format in unadapted form only, for noncommercial purposes only, and only so long as attribution is given to the creator.

